// utils/imageMap.ts
export const imageMap: {[key: string]: any} = {
  // Politics & Global Affairs
  'us-politics-1.png': require('../assets/generated-images/us-politics-1.png'),
  'us-politics-2.png': require('../assets/generated-images/us-politics-2.png'),
  'us-politics-3.png': require('../assets/generated-images/us-politics-3.png'),
  'us-politics-4.png': require('../assets/generated-images/us-politics-4.png'),
  'us-politics-5.png': require('../assets/generated-images/us-politics-5.png'),
  'us-politics-6.png': require('../assets/generated-images/us-politics-6.png'),
  'us-politics-7.png': require('../assets/generated-images/us-politics-7.png'),

  'indian-politics-1.png': require('../assets/generated-images/indian-politics-1.png'),
  'indian-politics-2.png': require('../assets/generated-images/indian-politics-2.png'),
  'indian-politics-3.png': require('../assets/generated-images/indian-politics-3.png'),
  'indian-politics-4.png': require('../assets/generated-images/indian-politics-4.png'),
  'indian-politics-5.png': require('../assets/generated-images/indian-politics-5.png'),
  'indian-politics-6.png': require('../assets/generated-images/indian-politics-6.png'),
  'indian-politics-7.png': require('../assets/generated-images/indian-politics-7.png'),

  'uk-politics-1.png': require('../assets/generated-images/uk-politics-1.png'),
  'uk-politics-2.png': require('../assets/generated-images/uk-politics-2.png'),
  'uk-politics-3.png': require('../assets/generated-images/uk-politics-3.png'),
  'uk-politics-4.png': require('../assets/generated-images/uk-politics-4.png'),
  'uk-politics-5.png': require('../assets/generated-images/uk-politics-5.png'),
  'uk-politics-6.png': require('../assets/generated-images/uk-politics-6.png'),
  'uk-politics-7.png': require('../assets/generated-images/uk-politics-7.png'),

  "china's-politics-1.png": require('../assets/generated-images/china’s-politics-1.png'),
  "china's-politics-2.png": require('../assets/generated-images/china’s-politics-2.png'),
  "china's-politics-3.png": require('../assets/generated-images/china’s-politics-3.png'),
  "china's-politics-4.png": require('../assets/generated-images/china’s-politics-4.png'),
  "china's-politics-5.png": require('../assets/generated-images/china’s-politics-5.png'),
  "china's-politics-6.png": require('../assets/generated-images/china’s-politics-6.png'),
  "china's-politics-7.png": require('../assets/generated-images/china’s-politics-7.png'),

  "russia's-geopolitics-1.png": require('../assets/generated-images/russia’s-geopolitics-1.png'),
  "russia's-geopolitics-2.png": require('../assets/generated-images/russia’s-geopolitics-2.png'),
  "russia's-geopolitics-3.png": require('../assets/generated-images/russia’s-geopolitics-3.png'),
  "russia's-geopolitics-4.png": require('../assets/generated-images/russia’s-geopolitics-4.png'),
  "russia's-geopolitics-5.png": require('../assets/generated-images/russia’s-geopolitics-5.png'),
  "russia's-geopolitics-6.png": require('../assets/generated-images/russia’s-geopolitics-6.png'),
  "russia's-geopolitics-7.png": require('../assets/generated-images/russia’s-geopolitics-7.png'),

  'eu-politics-1.png': require('../assets/generated-images/eu-politics-1.png'),
  'eu-politics-2.png': require('../assets/generated-images/eu-politics-2.png'),
  'eu-politics-3.png': require('../assets/generated-images/eu-politics-3.png'),
  'eu-politics-4.png': require('../assets/generated-images/eu-politics-4.png'),
  'eu-politics-5.png': require('../assets/generated-images/eu-politics-5.png'),
  'eu-politics-6.png': require('../assets/generated-images/eu-politics-6.png'),
  'eu-politics-7.png': require('../assets/generated-images/eu-politics-7.png'),

  'war-&-tensions-1.png': require('../assets/generated-images/war-&-tensions-1.png'),
  'war-&-tensions-2.png': require('../assets/generated-images/war-&-tensions-2.png'),
  'war-&-tensions-3.png': require('../assets/generated-images/war-&-tensions-3.png'),
  'war-&-tensions-4.png': require('../assets/generated-images/war-&-tensions-4.png'),
  'war-&-tensions-5.png': require('../assets/generated-images/war-&-tensions-5.png'),
  'war-&-tensions-6.png': require('../assets/generated-images/war-&-tensions-6.png'),
  'war-&-tensions-7.png': require('../assets/generated-images/war-&-tensions-7.png'),

  'superpower-moves-1.png': require('../assets/generated-images/superpower-moves-1.png'),
  'superpower-moves-2.png': require('../assets/generated-images/superpower-moves-2.png'),
  'superpower-moves-3.png': require('../assets/generated-images/superpower-moves-3.png'),
  'superpower-moves-4.png': require('../assets/generated-images/superpower-moves-4.png'),
  'superpower-moves-5.png': require('../assets/generated-images/superpower-moves-5.png'),
  'superpower-moves-6.png': require('../assets/generated-images/superpower-moves-6.png'),
  'superpower-moves-7.png': require('../assets/generated-images/superpower-moves-7.png'),

  // Business & Economy
  'vc-&-funding-1.png': require('../assets/generated-images/vc-&-funding-1.png'),
  'vc-&-funding-2.png': require('../assets/generated-images/vc-&-funding-2.png'),
  'vc-&-funding-3.png': require('../assets/generated-images/vc-&-funding-3.png'),
  'vc-&-funding-4.png': require('../assets/generated-images/vc-&-funding-4.png'),
  'vc-&-funding-5.png': require('../assets/generated-images/vc-&-funding-5.png'),
  'vc-&-funding-6.png': require('../assets/generated-images/vc-&-funding-6.png'),
  'vc-&-funding-7.png': require('../assets/generated-images/vc-&-funding-7.png'),

  'startups-1.png': require('../assets/generated-images/startups-1.png'),
  'startups-2.png': require('../assets/generated-images/startups-2.png'),
  'startups-3.png': require('../assets/generated-images/startups-3.png'),
  'startups-4.png': require('../assets/generated-images/startups-4.png'),
  'startups-5.png': require('../assets/generated-images/startups-5.png'),
  'startups-6.png': require('../assets/generated-images/startups-6.png'),
  'startups-7.png': require('../assets/generated-images/startups-7.png'),

  'stock-market-1.png': require('../assets/generated-images/stock-market-1.png'),
  'stock-market-2.png': require('../assets/generated-images/stock-market-2.png'),
  'stock-market-3.png': require('../assets/generated-images/stock-market-3.png'),
  'stock-market-4.png': require('../assets/generated-images/stock-market-4.png'),
  'stock-market-5.png': require('../assets/generated-images/stock-market-5.png'),
  'stock-market-6.png': require('../assets/generated-images/stock-market-6.png'),
  'stock-market-7.png': require('../assets/generated-images/stock-market-7.png'),

  'investment-trends-1.png': require('../assets/generated-images/investment-trends-1.png'),
  'investment-trends-2.png': require('../assets/generated-images/investment-trends-2.png'),
  'investment-trends-3.png': require('../assets/generated-images/investment-trends-3.png'),
  'investment-trends-4.png': require('../assets/generated-images/investment-trends-4.png'),
  'investment-trends-5.png': require('../assets/generated-images/investment-trends-5.png'),
  'investment-trends-6.png': require('../assets/generated-images/investment-trends-6.png'),
  'investment-trends-7.png': require('../assets/generated-images/investment-trends-7.png'),

  'layoffs-&-hires-1.png': require('../assets/generated-images/layoffs-&-hires-1.png'),
  'layoffs-&-hires-2.png': require('../assets/generated-images/layoffs-&-hires-2.png'),
  'layoffs-&-hires-3.png': require('../assets/generated-images/layoffs-&-hires-3.png'),
  'layoffs-&-hires-4.png': require('../assets/generated-images/layoffs-&-hires-4.png'),
  'layoffs-&-hires-5.png': require('../assets/generated-images/layoffs-&-hires-5.png'),
  'layoffs-&-hires-6.png': require('../assets/generated-images/layoffs-&-hires-6.png'),
  'layoffs-&-hires-7.png': require('../assets/generated-images/layoffs-&-hires-7.png'),

  'corporate-deals-1.png': require('../assets/generated-images/corporate-deals-1.png'),
  'corporate-deals-2.png': require('../assets/generated-images/corporate-deals-2.png'),
  'corporate-deals-3.png': require('../assets/generated-images/corporate-deals-3.png'),
  'corporate-deals-4.png': require('../assets/generated-images/corporate-deals-4.png'),
  'corporate-deals-5.png': require('../assets/generated-images/corporate-deals-5.png'),
  'corporate-deals-6.png': require('../assets/generated-images/corporate-deals-6.png'),
  'corporate-deals-7.png': require('../assets/generated-images/corporate-deals-7.png'),

  // New Categories
  'wrestling-&-combat-sports-1.png': require('../assets/generated-images/wrestling-&-combat-sports-1.png'),
  'wrestling-&-combat-sports-2.png': require('../assets/generated-images/wrestling-&-combat-sports-2.png'),
  'wrestling-&-combat-sports-3.png': require('../assets/generated-images/wrestling-&-combat-sports-3.png'),
  'wrestling-&-combat-sports-4.png': require('../assets/generated-images/wrestling-&-combat-sports-4.png'),
  'wrestling-&-combat-sports-5.png': require('../assets/generated-images/wrestling-&-combat-sports-5.png'),
  'wrestling-&-combat-sports-6.png': require('../assets/generated-images/wrestling-&-combat-sports-6.png'),
  'wrestling-&-combat-sports-7.png': require('../assets/generated-images/wrestling-&-combat-sports-7.png'),

  'violent-crimes-1.png': require('../assets/generated-images/violent-crimes-1.png'),
  'violent-crimes-2.png': require('../assets/generated-images/violent-crimes-2.png'),
  'violent-crimes-3.png': require('../assets/generated-images/violent-crimes-3.png'),
  'violent-crimes-4.png': require('../assets/generated-images/violent-crimes-4.png'),
  'violent-crimes-5.png': require('../assets/generated-images/violent-crimes-5.png'),
  'violent-crimes-6.png': require('../assets/generated-images/violent-crimes-6.png'),
  'violent-crimes-7.png': require('../assets/generated-images/violent-crimes-7.png'),

  'unusual-&-strange-news-1.png': require('../assets/generated-images/unusual-&-strange-news-1.png'),
  'unusual-&-strange-news-2.png': require('../assets/generated-images/unusual-&-strange-news-2.png'),
  'unusual-&-strange-news-3.png': require('../assets/generated-images/unusual-&-strange-news-3.png'),
  'unusual-&-strange-news-4.png': require('../assets/generated-images/unusual-&-strange-news-4.png'),
  'unusual-&-strange-news-5.png': require('../assets/generated-images/unusual-&-strange-news-5.png'),
  'unusual-&-strange-news-6.png': require('../assets/generated-images/unusual-&-strange-news-6.png'),
  'unusual-&-strange-news-7.png': require('../assets/generated-images/unusual-&-strange-news-7.png'),

  'traditional-&-alternative-medicine-1.png': require('../assets/generated-images/traditional-&-alternative-medicine-1.png'),
  'traditional-&-alternative-medicine-2.png': require('../assets/generated-images/traditional-&-alternative-medicine-2.png'),
  'traditional-&-alternative-medicine-3.png': require('../assets/generated-images/traditional-&-alternative-medicine-3.png'),
  'traditional-&-alternative-medicine-4.png': require('../assets/generated-images/traditional-&-alternative-medicine-4.png'),
  'traditional-&-alternative-medicine-5.png': require('../assets/generated-images/traditional-&-alternative-medicine-5.png'),
  'traditional-&-alternative-medicine-6.png': require('../assets/generated-images/traditional-&-alternative-medicine-6.png'),
  'traditional-&-alternative-medicine-7.png': require('../assets/generated-images/traditional-&-alternative-medicine-7.png'),

  'trade-wars-1.png': require('../assets/generated-images/trade-wars-1.png'),
  'trade-wars-2.png': require('../assets/generated-images/trade-wars-2.png'),
  'trade-wars-3.png': require('../assets/generated-images/trade-wars-3.png'),
  'trade-wars-4.png': require('../assets/generated-images/trade-wars-4.png'),
  'trade-wars-5.png': require('../assets/generated-images/trade-wars-5.png'),
  'trade-wars-6.png': require('../assets/generated-images/trade-wars-6.png'),
  'trade-wars-7.png': require('../assets/generated-images/trade-wars-7.png'),

  'terrorism-&-extremism-1.png': require('../assets/generated-images/terrorism-&-extremism-1.png'),
  'terrorism-&-extremism-2.png': require('../assets/generated-images/terrorism-&-extremism-2.png'),
  'terrorism-&-extremism-3.png': require('../assets/generated-images/terrorism-&-extremism-3.png'),
  'terrorism-&-extremism-4.png': require('../assets/generated-images/terrorism-&-extremism-4.png'),
  'terrorism-&-extremism-5.png': require('../assets/generated-images/terrorism-&-extremism-5.png'),
  'terrorism-&-extremism-6.png': require('../assets/generated-images/terrorism-&-extremism-6.png'),
  'terrorism-&-extremism-7.png': require('../assets/generated-images/terrorism-&-extremism-7.png'),

  // Science and Technology
  'artificial-intelligence-&-machine-learning-1.png': require('../assets/generated-images/artificial-intelligence-&-machine-learning-1.png'),
  'artificial-intelligence-&-machine-learning-2.png': require('../assets/generated-images/artificial-intelligence-&-machine-learning-2.png'),
  'artificial-intelligence-&-machine-learning-3.png': require('../assets/generated-images/artificial-intelligence-&-machine-learning-3.png'),
  'artificial-intelligence-&-machine-learning-4.png': require('../assets/generated-images/artificial-intelligence-&-machine-learning-4.png'),
  'artificial-intelligence-&-machine-learning-5.png': require('../assets/generated-images/artificial-intelligence-&-machine-learning-5.png'),
  'artificial-intelligence-&-machine-learning-6.png': require('../assets/generated-images/artificial-intelligence-&-machine-learning-6.png'),
  'artificial-intelligence-&-machine-learning-7.png': require('../assets/generated-images/artificial-intelligence-&-machine-learning-7.png'),

  'software-development-&-engineering-1.png': require('../assets/generated-images/software-development-&-engineering-1.png'),
  'software-development-&-engineering-2.png': require('../assets/generated-images/software-development-&-engineering-2.png'),
  'software-development-&-engineering-3.png': require('../assets/generated-images/software-development-&-engineering-3.png'),
  'software-development-&-engineering-4.png': require('../assets/generated-images/software-development-&-engineering-4.png'),
  'software-development-&-engineering-5.png': require('../assets/generated-images/software-development-&-engineering-5.png'),
  'software-development-&-engineering-6.png': require('../assets/generated-images/software-development-&-engineering-6.png'),
  'software-development-&-engineering-7.png': require('../assets/generated-images/software-development-&-engineering-7.png'),

  'data-science-1.png': require('../assets/generated-images/data-science-1.png'),
  'data-science-2.png': require('../assets/generated-images/data-science-2.png'),
  'data-science-3.png': require('../assets/generated-images/data-science-3.png'),
  'data-science-4.png': require('../assets/generated-images/data-science-4.png'),
  'data-science-5.png': require('../assets/generated-images/data-science-5.png'),
  'data-science-6.png': require('../assets/generated-images/data-science-6.png'),
  'data-science-7.png': require('../assets/generated-images/data-science-7.png'),

  'space-exploration-&-astronomy-1.png': require('../assets/generated-images/space-exploration-&-astronomy-1.png'),
  'space-exploration-&-astronomy-2.png': require('../assets/generated-images/space-exploration-&-astronomy-2.png'),
  'space-exploration-&-astronomy-3.png': require('../assets/generated-images/space-exploration-&-astronomy-3.png'),
  'space-exploration-&-astronomy-4.png': require('../assets/generated-images/space-exploration-&-astronomy-4.png'),
  'space-exploration-&-astronomy-5.png': require('../assets/generated-images/space-exploration-&-astronomy-5.png'),
  'space-exploration-&-astronomy-6.png': require('../assets/generated-images/space-exploration-&-astronomy-6.png'),
  'space-exploration-&-astronomy-7.png': require('../assets/generated-images/space-exploration-&-astronomy-7.png'),

  'health-&-biotech-innovations-1.png': require('../assets/generated-images/health-&-biotech-innovations-1.png'),
  'health-&-biotech-innovations-2.png': require('../assets/generated-images/health-&-biotech-innovations-2.png'),
  'health-&-biotech-innovations-3.png': require('../assets/generated-images/health-&-biotech-innovations-3.png'),
  'health-&-biotech-innovations-4.png': require('../assets/generated-images/health-&-biotech-innovations-4.png'),
  'health-&-biotech-innovations-5.png': require('../assets/generated-images/health-&-biotech-innovations-5.png'),
  'health-&-biotech-innovations-6.png': require('../assets/generated-images/health-&-biotech-innovations-6.png'),
  'health-&-biotech-innovations-7.png': require('../assets/generated-images/health-&-biotech-innovations-7.png'),

  'cybersecurity-&-data-privacy-1.png': require('../assets/generated-images/cybersecurity-&-data-privacy-1.png'),
  'cybersecurity-&-data-privacy-2.png': require('../assets/generated-images/cybersecurity-&-data-privacy-2.png'),
  'cybersecurity-&-data-privacy-3.png': require('../assets/generated-images/cybersecurity-&-data-privacy-3.png'),
  'cybersecurity-&-data-privacy-4.png': require('../assets/generated-images/cybersecurity-&-data-privacy-4.png'),
  'cybersecurity-&-data-privacy-5.png': require('../assets/generated-images/cybersecurity-&-data-privacy-5.png'),
  'cybersecurity-&-data-privacy-6.png': require('../assets/generated-images/cybersecurity-&-data-privacy-6.png'),
  'cybersecurity-&-data-privacy-7.png': require('../assets/generated-images/cybersecurity-&-data-privacy-7.png'),

  // Health and Wellness
  'medical-breakthroughs-&-innovations-1.png': require('../assets/generated-images/medical-breakthroughs-&-innovations-1.png'),
  'medical-breakthroughs-&-innovations-2.png': require('../assets/generated-images/medical-breakthroughs-&-innovations-2.png'),
  'medical-breakthroughs-&-innovations-3.png': require('../assets/generated-images/medical-breakthroughs-&-innovations-3.png'),
  'medical-breakthroughs-&-innovations-4.png': require('../assets/generated-images/medical-breakthroughs-&-innovations-4.png'),
  'medical-breakthroughs-&-innovations-5.png': require('../assets/generated-images/medical-breakthroughs-&-innovations-5.png'),
  'medical-breakthroughs-&-innovations-6.png': require('../assets/generated-images/medical-breakthroughs-&-innovations-6.png'),
  'medical-breakthroughs-&-innovations-7.png': require('../assets/generated-images/medical-breakthroughs-&-innovations-7.png'),

  'mental-health-&-well-being-1.png': require('../assets/generated-images/mental-health-&-well-being-1.png'),
  'mental-health-&-well-being-2.png': require('../assets/generated-images/mental-health-&-well-being-2.png'),
  'mental-health-&-well-being-3.png': require('../assets/generated-images/mental-health-&-well-being-3.png'),
  'mental-health-&-well-being-4.png': require('../assets/generated-images/mental-health-&-well-being-4.png'),
  'mental-health-&-well-being-5.png': require('../assets/generated-images/mental-health-&-well-being-5.png'),
  'mental-health-&-well-being-6.png': require('../assets/generated-images/mental-health-&-well-being-6.png'),
  'mental-health-&-well-being-7.png': require('../assets/generated-images/mental-health-&-well-being-7.png'),

  'fitness-&-exercise-trends-1.png': require('../assets/generated-images/fitness-&-exercise-trends-1.png'),
  'fitness-&-exercise-trends-2.png': require('../assets/generated-images/fitness-&-exercise-trends-2.png'),
  'fitness-&-exercise-trends-3.png': require('../assets/generated-images/fitness-&-exercise-trends-3.png'),
  'fitness-&-exercise-trends-4.png': require('../assets/generated-images/fitness-&-exercise-trends-4.png'),
  'fitness-&-exercise-trends-5.png': require('../assets/generated-images/fitness-&-exercise-trends-5.png'),
  'fitness-&-exercise-trends-6.png': require('../assets/generated-images/fitness-&-exercise-trends-6.png'),
  'fitness-&-exercise-trends-7.png': require('../assets/generated-images/fitness-&-exercise-trends-7.png'),

  'nutrition-&-diet-1.png': require('../assets/generated-images/nutrition-&-diet-1.png'),
  'nutrition-&-diet-2.png': require('../assets/generated-images/nutrition-&-diet-2.png'),
  'nutrition-&-diet-3.png': require('../assets/generated-images/nutrition-&-diet-3.png'),
  'nutrition-&-diet-4.png': require('../assets/generated-images/nutrition-&-diet-4.png'),
  'nutrition-&-diet-5.png': require('../assets/generated-images/nutrition-&-diet-5.png'),
  'nutrition-&-diet-6.png': require('../assets/generated-images/nutrition-&-diet-6.png'),
  'nutrition-&-diet-7.png': require('../assets/generated-images/nutrition-&-diet-7.png'),

  // Sports
  'football-1.png': require('../assets/generated-images/football-1.png'),
  'football-2.png': require('../assets/generated-images/football-2.png'),
  'football-3.png': require('../assets/generated-images/football-3.png'),
  'football-4.png': require('../assets/generated-images/football-4.png'),
  'football-5.png': require('../assets/generated-images/football-5.png'),
  'football-6.png': require('../assets/generated-images/football-6.png'),
  'football-7.png': require('../assets/generated-images/football-7.png'),

  'cricket-1.png': require('../assets/generated-images/cricket-1.png'),
  'cricket-2.png': require('../assets/generated-images/cricket-2.png'),
  'cricket-3.png': require('../assets/generated-images/cricket-3.png'),
  'cricket-4.png': require('../assets/generated-images/cricket-4.png'),
  'cricket-5.png': require('../assets/generated-images/cricket-5.png'),
  'cricket-6.png': require('../assets/generated-images/cricket-6.png'),
  'cricket-7.png': require('../assets/generated-images/cricket-7.png'),

  'olympics-&-major-events-1.png': require('../assets/generated-images/olympics-&-major-events-1.png'),
  'olympics-&-major-events-2.png': require('../assets/generated-images/olympics-&-major-events-2.png'),
  'olympics-&-major-events-3.png': require('../assets/generated-images/olympics-&-major-events-3.png'),
  'olympics-&-major-events-4.png': require('../assets/generated-images/olympics-&-major-events-4.png'),
  'olympics-&-major-events-5.png': require('../assets/generated-images/olympics-&-major-events-5.png'),
  'olympics-&-major-events-6.png': require('../assets/generated-images/olympics-&-major-events-6.png'),
  'olympics-&-major-events-7.png': require('../assets/generated-images/olympics-&-major-events-7.png'),

  'basketball-&-nba-1.png': require('../assets/generated-images/basketball-&-nba-1.png'),
  'basketball-&-nba-2.png': require('../assets/generated-images/basketball-&-nba-2.png'),
  'basketball-&-nba-3.png': require('../assets/generated-images/basketball-&-nba-3.png'),
  'basketball-&-nba-4.png': require('../assets/generated-images/basketball-&-nba-4.png'),
  'basketball-&-nba-5.png': require('../assets/generated-images/basketball-&-nba-5.png'),
  'basketball-&-nba-6.png': require('../assets/generated-images/basketball-&-nba-6.png'),
  'basketball-&-nba-7.png': require('../assets/generated-images/basketball-&-nba-7.png'),

  'esports-&-gaming-1.png': require('../assets/generated-images/esports-&-gaming-1.png'),
  'esports-&-gaming-2.png': require('../assets/generated-images/esports-&-gaming-2.png'),
  'esports-&-gaming-3.png': require('../assets/generated-images/esports-&-gaming-3.png'),
  'esports-&-gaming-4.png': require('../assets/generated-images/esports-&-gaming-4.png'),
  'esports-&-gaming-5.png': require('../assets/generated-images/esports-&-gaming-5.png'),
  'esports-&-gaming-6.png': require('../assets/generated-images/esports-&-gaming-6.png'),
  'esports-&-gaming-7.png': require('../assets/generated-images/esports-&-gaming-7.png'),

  'badminton-&-other-racquet-sports-1.png': require('../assets/generated-images/badminton-&-other-racquet-sports-1.png'),
  'badminton-&-other-racquet-sports-2.png': require('../assets/generated-images/badminton-&-other-racquet-sports-2.png'),
  'badminton-&-other-racquet-sports-3.png': require('../assets/generated-images/badminton-&-other-racquet-sports-3.png'),
  'badminton-&-other-racquet-sports-4.png': require('../assets/generated-images/badminton-&-other-racquet-sports-4.png'),
  'badminton-&-other-racquet-sports-5.png': require('../assets/generated-images/badminton-&-other-racquet-sports-5.png'),
  'badminton-&-other-racquet-sports-6.png': require('../assets/generated-images/badminton-&-other-racquet-sports-6.png'),
  'badminton-&-other-racquet-sports-7.png': require('../assets/generated-images/badminton-&-other-racquet-sports-7.png'),

  'american-football-&-rugby-1.png': require('../assets/generated-images/american-football-&-rugby-1.png'),
  'american-football-&-rugby-2.png': require('../assets/generated-images/american-football-&-rugby-2.png'),
  'american-football-&-rugby-3.png': require('../assets/generated-images/american-football-&-rugby-3.png'),
  'american-football-&-rugby-4.png': require('../assets/generated-images/american-football-&-rugby-4.png'),
  'american-football-&-rugby-5.png': require('../assets/generated-images/american-football-&-rugby-5.png'),
  'american-football-&-rugby-6.png': require('../assets/generated-images/american-football-&-rugby-6.png'),
  'american-football-&-rugby-7.png': require('../assets/generated-images/american-football-&-rugby-7.png'),

  // Entertainment and Celebrity News
  'movies-&-tv-shows-1.png': require('../assets/generated-images/movies-&-tv-shows-1.png'),
  'movies-&-tv-shows-2.png': require('../assets/generated-images/movies-&-tv-shows-2.png'),
  'movies-&-tv-shows-3.png': require('../assets/generated-images/movies-&-tv-shows-3.png'),
  'movies-&-tv-shows-4.png': require('../assets/generated-images/movies-&-tv-shows-4.png'),
  'movies-&-tv-shows-5.png': require('../assets/generated-images/movies-&-tv-shows-5.png'),
  'movies-&-tv-shows-6.png': require('../assets/generated-images/movies-&-tv-shows-6.png'),
  'movies-&-tv-shows-7.png': require('../assets/generated-images/movies-&-tv-shows-7.png'),

  'celebrity-gossip-&-lifestyle-1.png': require('../assets/generated-images/celebrity-gossip-&-lifestyle-1.png'),
  'celebrity-gossip-&-lifestyle-2.png': require('../assets/generated-images/celebrity-gossip-&-lifestyle-2.png'),
  'celebrity-gossip-&-lifestyle-3.png': require('../assets/generated-images/celebrity-gossip-&-lifestyle-3.png'),
  'celebrity-gossip-&-lifestyle-4.png': require('../assets/generated-images/celebrity-gossip-&-lifestyle-4.png'),
  'celebrity-gossip-&-lifestyle-5.png': require('../assets/generated-images/celebrity-gossip-&-lifestyle-5.png'),
  'celebrity-gossip-&-lifestyle-6.png': require('../assets/generated-images/celebrity-gossip-&-lifestyle-6.png'),
  'celebrity-gossip-&-lifestyle-7.png': require('../assets/generated-images/celebrity-gossip-&-lifestyle-7.png'),

  'music-&-concerts-1.png': require('../assets/generated-images/music-&-concerts-1.png'),
  'music-&-concerts-2.png': require('../assets/generated-images/music-&-concerts-2.png'),
  'music-&-concerts-3.png': require('../assets/generated-images/music-&-concerts-3.png'),
  'music-&-concerts-4.png': require('../assets/generated-images/music-&-concerts-4.png'),
  'music-&-concerts-5.png': require('../assets/generated-images/music-&-concerts-5.png'),
  'music-&-concerts-6.png': require('../assets/generated-images/music-&-concerts-6.png'),
  'music-&-concerts-7.png': require('../assets/generated-images/music-&-concerts-7.png'),

  'bollywood-1.png': require('../assets/generated-images/bollywood-1.png'),
  'bollywood-2.png': require('../assets/generated-images/bollywood-2.png'),
  'bollywood-3.png': require('../assets/generated-images/bollywood-3.png'),
  'bollywood-4.png': require('../assets/generated-images/bollywood-4.png'),
  'bollywood-5.png': require('../assets/generated-images/bollywood-5.png'),
  'bollywood-6.png': require('../assets/generated-images/bollywood-6.png'),
  'bollywood-7.png': require('../assets/generated-images/bollywood-7.png'),

  'hollywood-1.png': require('../assets/generated-images/hollywood-1.png'),
  'hollywood-2.png': require('../assets/generated-images/hollywood-2.png'),
  'hollywood-3.png': require('../assets/generated-images/hollywood-3.png'),
  'hollywood-4.png': require('../assets/generated-images/hollywood-4.png'),
  'hollywood-5.png': require('../assets/generated-images/hollywood-5.png'),
  'hollywood-6.png': require('../assets/generated-images/hollywood-6.png'),
  'hollywood-7.png': require('../assets/generated-images/hollywood-7.png'),

  'k-dramas-1.png': require('../assets/generated-images/k-dramas-1.png'),
  'k-dramas-2.png': require('../assets/generated-images/k-dramas-2.png'),
  'k-dramas-3.png': require('../assets/generated-images/k-dramas-3.png'),
  'k-dramas-4.png': require('../assets/generated-images/k-dramas-4.png'),
  'k-dramas-5.png': require('../assets/generated-images/k-dramas-5.png'),
  'k-dramas-6.png': require('../assets/generated-images/k-dramas-6.png'),
  'k-dramas-7.png': require('../assets/generated-images/k-dramas-7.png'),

  // Crime and Public Safety
  'cybercrime-&-online-scams-1.png': require('../assets/generated-images/cybercrime-&-online-scams-1.png'),
  'cybercrime-&-online-scams-2.png': require('../assets/generated-images/cybercrime-&-online-scams-2.png'),
  'cybercrime-&-online-scams-3.png': require('../assets/generated-images/cybercrime-&-online-scams-3.png'),
  'cybercrime-&-online-scams-4.png': require('../assets/generated-images/cybercrime-&-online-scams-4.png'),
  'cybercrime-&-online-scams-5.png': require('../assets/generated-images/cybercrime-&-online-scams-5.png'),
  'cybercrime-&-online-scams-6.png': require('../assets/generated-images/cybercrime-&-online-scams-6.png'),
  'cybercrime-&-online-scams-7.png': require('../assets/generated-images/cybercrime-&-online-scams-7.png'),

  // Human Interest Stories
  'viral-&-social-media-trends-1.png': require('../assets/generated-images/viral-&-social-media-trends-1.png'),
  'viral-&-social-media-trends-2.png': require('../assets/generated-images/viral-&-social-media-trends-2.png'),
  'viral-&-social-media-trends-3.png': require('../assets/generated-images/viral-&-social-media-trends-3.png'),
  'viral-&-social-media-trends-4.png': require('../assets/generated-images/viral-&-social-media-trends-4.png'),
  'viral-&-social-media-trends-5.png': require('../assets/generated-images/viral-&-social-media-trends-5.png'),
  'viral-&-social-media-trends-6.png': require('../assets/generated-images/viral-&-social-media-trends-6.png'),
  'viral-&-social-media-trends-7.png': require('../assets/generated-images/viral-&-social-media-trends-7.png'),

  // Fallback images
  technology: require('../assets/tech.png'),
  sports: require('../assets/sports.png'),
  health: require('../assets/health.png'),
  entertainment: require('../assets/entertainment.png'),
  business: require('../assets/economics.png'),
  economics: require('../assets/economics.png'),
};
